Ruby/lab05/config/routes.rb
Rails.application.routes.draw do
  get 'news/news'

  get 'news/branches/:identifier', to: 'news#branches'

  get 'news/authors/:identifier', to: 'news#authors'
  
  get 'news/addArticle', to: 'news#addArticle'

  root 'news#news'

  resources :articles
  resources :branches
  resources :authors

end

Ruby/lab05/app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :author
	belongs_to :branch
end

Ruby/lab05/app/models/author.rb
class Author < ActiveRecord::Base
	has_many :articles
end

Ruby/lab05/app/models/branch.rb
class Branch < ActiveRecord::Base
	has_many :articles
end

Ruby/lab05/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Ruby/lab05/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:branch_id, :author_id, :title, :text)
    end
end

Ruby/lab05/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name)
    end
end

Ruby/lab05/app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_branch, only: [:show, :edit, :update, :destroy]

  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.all
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
  end

  # GET /branches/new
  def new
    @branch = Branch.new
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to @branch, notice: 'Branch was successfully created.' }
        format.json { render :show, status: :created, location: @branch }
      else
        format.html { render :new }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1
  # PATCH/PUT /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to @branch, notice: 'Branch was successfully updated.' }
        format.json { render :show, status: :ok, location: @branch }
      else
        format.html { render :edit }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to branches_url, notice: 'Branch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def branch_params
      params.require(:branch).permit(:branch)
    end
end

Ruby/lab05/app/controllers/news_controller.rb
class NewsController < ApplicationController
  def news
	  @article_list = Article.all
  end

  def branches
	  @branch = Branch.find_by(id: params["identifier"])
  end

  def authors
	  @author = Author.find_by(id: params["identifier"])
  end

  def addArticle
	@branches = Branch.all
	@authors = Author.all
  end

  def addBranch
	
  end

  def addAuthor

  end
end

Ruby/lab05/app/helpers/application_helper.rb
module ApplicationHelper
end

Ruby/lab05/app/helpers/articles_helper.rb
module ArticlesHelper
end

Ruby/lab05/app/helpers/authors_helper.rb
module AuthorsHelper
end

Ruby/lab05/app/helpers/branches_helper.rb
module BranchesHelper
end

Ruby/lab05/app/helpers/news_helper.rb
module NewsHelper
end

Ruby/lab05/app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :branch_id %><br>
    <%= f.number_field :branch_id %>
  </div>
  <div class="field">
    <%= f.label :author_id %><br>
    <%= f.number_field :author_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Ruby/lab05/app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

Ruby/lab05/app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th>Branch</th>
      <th>Author</th>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.branch.branch %></td>
        <td><%= article.author.name %></td>
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

Ruby/lab05/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

Ruby/lab05/app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Branch:</strong>
  <%= @article.branch_id %>
</p>

<p>
  <strong>Author:</strong>
  <%= @article.author_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

Ruby/lab05/app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Ruby/lab05/app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

Ruby/lab05/app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

Ruby/lab05/app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

Ruby/lab05/app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

Ruby/lab05/app/views/branches/_form.html.erb
<%= form_for(@branch) do |f| %>
  <% if @branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@branch.errors.count, "error") %> prohibited this branch from being saved:</h2>

      <ul>
      <% @branch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :branch %><br>
    <%= f.text_field :branch %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Ruby/lab05/app/views/branches/edit.html.erb
<h1>Editing Branch</h1>

<%= render 'form' %>

<%= link_to 'Show', @branch %> |
<%= link_to 'Back', branches_path %>

Ruby/lab05/app/views/branches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Branches</h1>

<table>
  <thead>
    <tr>
      <th>Branch</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @branches.each do |branch| %>
      <tr>
        <td><%= branch.branch %></td>
        <td><%= link_to 'Show', branch %></td>
        <td><%= link_to 'Edit', edit_branch_path(branch) %></td>
        <td><%= link_to 'Destroy', branch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Branch', new_branch_path %>

Ruby/lab05/app/views/branches/new.html.erb
<h1>New Branch</h1>

<%= render 'form' %>

<%= link_to 'Back', branches_path %>

Ruby/lab05/app/views/branches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Branch:</strong>
  <%= @branch.branch %>
</p>

<%= link_to 'Edit', edit_branch_path(@branch) %> |
<%= link_to 'Back', branches_path %>

Ruby/lab05/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lab05</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Ruby/lab05/app/views/news/addArticle.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Add new article</title>
	<style>
		h1, p, table, a {
			color: #20C20E;
			text-align: center;
		}
		table {
			border-collapse: collapse;
			border-color: #20C20E;
			margin-bottom: 50px;
		}
	</style>
	<link rel="stylesheet" media="all" href="/assets/articles.self-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css?body=1" data-turbolinks-track="true" />
	<link rel="stylesheet" media="all" href="/assets/authors.self-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css?body=1" data-turbolinks-track="true" />
	<link rel="stylesheet" media="all" href="/assets/branches.self-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css?body=1" data-turbolinks-track="true" />
	<link rel="stylesheet" media="all" href="/assets/news.self-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.css?body=1" data-turbolinks-track="true" />
	<link rel="stylesheet" media="all" href="/assets/scaffolds.self-04c87a3b226970aaa6264a85050301903a30572fb1672f46556705b04deac3a1.css?body=1" data-turbolinks-track="true" />
	<link rel="stylesheet" media="all" href="/assets/application.self-e80e8f2318043e8af94dddc2adad5a4f09739a8ebb323b3ab31cd71d45fd9113.css?body=1" data-turbolinks-track="true" />
	  <script src="/assets/jquery.self-bd7ddd393353a8d2480a622e80342adf488fb6006d667e8b42e4c0073393abee.js?body=1" data-turbolinks-track="true"></script>
	<script src="/assets/jquery_ujs.self-784a997f6726036b1993eb2217c9cb558e1cbb801c6da88105588c56f13b466a.js?body=1" data-turbolinks-track="true"></script>
	<script src="/assets/turbolinks.self-2db6ec539b9190f75e1d477b305df53d12904d5cafdd47c7ffd91ba25cbec128.js?body=1" data-turbolinks-track="true"></script>
	<script src="/assets/articles.self-877aef30ae1b040ab8a3aba4e3e309a11d7f2612f44dde450b5c157aa5f95c05.js?body=1" data-turbolinks-track="true"></script>
	<script src="/assets/authors.self-877aef30ae1b040ab8a3aba4e3e309a11d7f2612f44dde450b5c157aa5f95c05.js?body=1" data-turbolinks-track="true"></script>
	<script src="/assets/branches.self-877aef30ae1b040ab8a3aba4e3e309a11d7f2612f44dde450b5c157aa5f95c05.js?body=1" data-turbolinks-track="true"></script>
	<script src="/assets/news.self-877aef30ae1b040ab8a3aba4e3e309a11d7f2612f44dde450b5c157aa5f95c05.js?body=1" data-turbolinks-track="true"></script>
	<script src="/assets/application.self-3b8dabdc891efe46b9a144b400ad69e37d7e5876bdc39dee783419a69d7ca819.js?body=1" data-turbolinks-track="true"></script>
	  <meta name="csrf-param" content="authenticity_token" />
	<meta name="csrf-token" content="OyYkkvde4kGzt8+AZJ1pdr2QOCZuPA3uH4ue5mGNJxW/ZHmPrT4ntQJaYnu4gIPwTjbAjY7BqRqJwoBdCxRSxw==" />
</head>
<body style="background-color: black;">
	<h1>Create new article</h1>
	<div style="color:#20C20E; text-align: center;">
		<form class="new_article" id="new_article" action="/articles" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="s5As2uR5q2N0jUDG7f5JAMxK0F2eGOObh/ygnJ5hS5k30nHHvhlul8Vg7T0x46OGP+wo9n7lR28Rtb4n9Pg+Sw==" />
		  <div class="field">
		    <label for="article_branch_id">Branch</label><br>
		    <select name="article[branch_id]" id="article_branch_id">
		    	<% for @branch in @branches %>
					<option value="<%= @branch.id %>"><%= @branch.branch %></option>
				<% end %>
		    </select>
		  </div>
		  <div class="field">
		    <label for="article_author_id">Author</label><br>
		   <!-- <input type="number" name="article[author_id]" id="article_author_id" style="width:60%;"/> -->
		   <select name="article[author_id]" id="article_author_id">
			    <% for @author in @authors %>
				    	<option value="<%= @author.id %>"><%= @author.name %></option>
			    <% end %>
		    </select>
		  </div>
		  <div class="field">
		    <label for="article_title">Title</label><br>
		    <input type="text" name="article[title]" id="article_title" style="width:60%;"/>
		  </div>
		  <div class="field">
		    <label for="article_text">Text</label><br>
		    <textarea name="article[text]" id="article_text" style="width:60%; height: 50px;" value="" placeholder="Put article text here">
		</textarea>
		  </div>
		  <div class="actions">
		    <input type="submit" name="commit" value="Create Article" />
		  </div>
		</form>
	</div>
</body>
</html>

Ruby/lab05/app/views/news/authors.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>News by <%= @author.name %></title>
	<style>
		h1, p, table, a {
			color: #20C20E;
			text-align: center;
		}
		table {
			border-collapse: collapse;
			border-color: #20C20E;
			margin-bottom: 50px;
		}
	</style>
</head>
<body style="background-color: black;">
	<h1> Here placed all news which posted by <%= @author.name %></h1>
	<% for @article in @author.articles %>
		<table align="center" border="1" width="80%">
			<tr>
				<td> Author: <a href="/news/authors/<%= @article.author.id %>"><%= @article.author.name %></a></td>
				<td> Branch: <a href="/news/branches/<%= @article.branch.id %>"><%= @article.branch.branch %></a> </td>
				<td> Date: <%= @article.created_at %></td>
			</tr>
			<tr>
				<td colspan="3"> Title: <%= @article.title %></td>
			</tr>
			<tr>
				<td colspan="3" height="100"> <%= @article.text %></td>
			</tr>
		</table>
	<% end %>
</body>
</html>

Ruby/lab05/app/views/news/branches.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Articles in branch <%= @branch.branch %></title>
	<style>
		h1, p, table, a {
			color: #20C20E;
			text-align: center;
		}
		table {
			border-collapse: collapse;
			border-color: #20C20E;
			margin-bottom: 50px;
		}
	</style>
</head>
<body style="background-color: black;">
	<h1> Here placed all news in branch <%= @branch.branch %></h1>
	<% for @article in @branch.articles %>
		<table align="center" border="1" width="80%">
			<tr>
				<td> Author: <a href="/news/authors/<%= @article.author.id %>"><%= @article.author.name %></a></td>
				<td> Branch: <a href="/news/branches/<%= @article.branch.id %>"><%= @article.branch.branch %></a> </td>
				<td> Date: <%= @article.created_at %></td>
			</tr>
			<tr>
				<td colspan="3"> Title: <%= @article.title %></td>
			</tr>
			<tr>
				<td colspan="3" height="100"> <%= @article.text %></td>
			</tr>
		</table>
	<% end %>
</body>
</html>

Ruby/lab05/app/views/news/news.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>News</title>
	<style>
		h1, p, table, a {
			color: #20C20E;
			text-align: center;
		}
		table {
			border-collapse: collapse;
			border-color: #20C20E;
			margin-bottom: 50px;
		}
	</style>
</head>
<body style="background-color: black;">
	<h1> Here placed all news</h1>
	<% for @article in @article_list %>
		<table align="center" border="1" width="80%">
			<tr>
				<td> Author: <a href="/news/authors/<%= @article.author.id %>"><%= @article.author.name %></a></td>
				<td> Branch: <a href="/news/branches/<%= @article.branch.id %>"><%= @article.branch.branch %></a> </td>
				<td> Date: <%= @article.created_at %></td>
			</tr>
			<tr>
				<td colspan="3"> Title: <%= @article.title %></td>
			</tr>
			<tr>
				<td colspan="3" height="100"> <%= @article.text %></td>
			</tr>
		</table>
	<% end %>
	<a href="/news/addArticle"><p>Create new article</p></a>
</body>
</html>